---
title: FamCHESS Results
author:
  - name: Kendra Wyant
  - name: John J. Curtin 
date: last-modified
bibliography: references.bib
number-sections: false 
editor_options: 
  chunk_output_type: console
---

## Results

### Demographics

### Study Arm Effects

From Protocol Paper:   

*Linear mixed models will be used to assess effects of study arm on each of our primary and secondary outcomes over time. There will be fixed effects for study arm, time, and their interaction. When applicable, a fixed effect will be added for the baseline values of the outcome variables. A by-subject random intercept and by-subject random slope for time will be included to accommodate the repeated measures on time. Time will be measured quantitatively (in months) and centered at the end of the intervention period (8 months).  Baseline scores on the outcomes will be mean centered.*  

*Study hypotheses will focus on the test of the parameter estimates for the two study arm effects. We will also test the study arm by time interaction to determine if the study arm effect is consistent or varies in magnitude over the intervention period. If significant study arm by time effects are observed, we will test simple effects of study arm at the timepoints (4, 8, and 12 months).*  

*We will consider a number of potential covariates as listed previously. Of this list, those variables that significantly predict our primary outcomes will be included in the final analysis.*

#### Primary Outcomes

#### Secondary Outcomes

### Mediator Effects

From Protocol Paper:  

*We will test for mediators of the study arm effects on our primary outcomes (IP % risky drinking days, dyad psychological distress) using the Joint Test of Significance method that has been recommended for its balance with respect to Type 1 and 2 error rates.a,b  To establish mediation, this method requires and simultaneously tests that both the effect of study arm on the mediator (α) and the effect of the mediator on the outcome (β) are jointly significant. Separate mediation analyses will be conducted for each combination of mediator and outcome. Measures of the mediators will be obtained at 4 months, and measures of the outcomes will be obtained at 8 months. Both mediator and outcome measures will be adjusted for their respective baseline values when baseline measures are available.*

### Moderator Effects

From Protocol Paper:  

*Analyses of study arm moderators including patient and partner gender (two variables, each man vs. women), type of relationship at baseline (romantic partner, family, other), partner relationship satisfaction (at baseline) will be conducted in follow-up analyses that add each moderator separately to the linear mixed models described above. Specifically, we will add fixed effects for the moderator and its interactions with study arm contrasts. Study hypotheses about moderation will focus on the test of the parameter estimates for the study arm contrasts by moderator interaction effects.*


### Missing Data 

From Protocol Paper:   

*In previous RCTs, we completed 85% of interviews through 12 months and limited missing data on core interview items to about 2%; we expect similar rates in this study. In SUD studies, data are not likely to be missing at random (i.e., the probability that data are missing relates to what the data would have been had the data been observed).c  We will conduct a sensitivity analysis on missing data, using logistic regression in order to examine whether dropout at follow-up is associated with observed/assigned factors, covariates, or outcomes at baseline. If missing data affects power or is significantly not missing at random, linear mixed models or multiple imputation will be used.*



## References

::: {#refs}
:::



